Add Apollo 11 picture of Earth from NASA
BuddiesOfBudgie/budgie-backgrounds pull request #5
Opened 2022-08-31 11:46 UTC by win8linux

## Description

Picture of the Earth from the Apollo 11 mission of NASA

### Image Information

- Author: NASA
- License: Public Domain
- Source: [Webpage](https://images.nasa.gov/details-as11-44-6551), [Original image](https://images-assets.nasa.gov/image/as11-44-6551/as11-44-6551~orig.jpg)

Source image has been cropped to 4,152 × 2,336 size.

### Submitter Checklist

- [x] Submitter has reviewed the Image Requirements
- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Updated the respective `meson.build` and `xml.in` files

2022-08-31 16:15 UTC, serebit requested changes
Great pic that I would support adding, but there are some things that need to be addressed first.

2022-08-31 16:15 UTC, serebit commented on backgrounds/meson.build
> +    'temp2.png'
Removing the comma here breaks the build.

2022-08-31 16:15 UTC, serebit commented on data/budgie-backgrounds.xml.in
> +    <name>apollo-11-earth.jpg</name>
Should change to "Earth from Apollo 11".

2022-09-07 16:16 UTC, JoshStrobl requested changes
Needs fixes from @serebit's review otherwise LGTM

2022-09-07 16:32 UTC, merged